/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FastEMD_emd_hat */

#ifndef _Included_FastEMD_emd_hat
#define _Included_FastEMD_emd_hat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FastEMD_emd_hat
 * Method:    native_dist_compute
 * Signature: ([D[D[DD[DIII)D
 */
JNIEXPORT jdouble JNICALL Java_FastEMD_emd_1hat_native_1dist_1compute
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
